package model.graphics;

public enum SpriteID {
    TILE_FLOOR,
    TILE_WALL,
    TILE_TRAP,
    PLAYER,
    ENTITY_DUMMY,
    ENTITY_GUARD,
    ITEM_HEALING_POTION,
    ITEM_DEFENSE_POTION,
    ITEM_STRENGTH_POTION,
    ITEM_GUARD_ARMOR,
    ITEM_GUARD_SWORD,
    UNKNOWN
}
