package model.graphics;

public enum SpriteID {
    TILE_FLOOR,
    TILE_WALL,
    TILE_TRAP,
    PLAYER,
    ENTITY_DUMMY,
    ENTITY_GUARD,
    ITEM_HEALING_POTION,
    ITEM_DEFENSE_POTION,
    ITEM_STRENGTH_POTION,
    ITEM_GUARD_ARMOR,
    ITEM_GUARD_SWORD,
    SPRITE_HEART_FULL,
    SPRITE_HEART_EMPTY,
    SPRITE_ARMOR_FULL,
    SPRITE_ARMOR_EMPTY,
    SPRITE_STRENGTH,
    SELECT_BLUE,
    SELECT_GREEN,
    SELECT_RED,
    PARTICLE_STUN,
    UNKNOWN
}
